"""Create reader table and add fk to books for reader

Revision ID: 2a6e09cfafd0
Revises: 4c4ce3e040fc
Create Date: 2022-06-25 13:55:59.055397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6e09cfafd0'
down_revision = '4c4ce3e040fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reader_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'readers', ['reader_pk'], ['pk'])
    op.add_column('readers', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('readers', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.drop_column('readers', 'readerName')
    op.drop_column('readers', 'readerAge')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readers', sa.Column('readerAge', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('readers', sa.Column('readerName', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('readers', 'last_name')
    op.drop_column('readers', 'first_name')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'reader_pk')
    # ### end Alembic commands ###
