"""Initial migration.

Revision ID: 4c4ce3e040fc
Revises: 
Create Date: 2022-06-24 23:40:42.376798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4ce3e040fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    op.create_table('readers',
    sa.Column('pk', sa.Integer(), nullable=False),
    sa.Column('readerName', sa.String(length=255), nullable=False),
    sa.Column('readerAge', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readers')
    op.drop_table('books')
    # ### end Alembic commands ###
